import { Player, PlayerStats } from "../models/Players";

export const mockPlayer = (): Player => {
    return {
        info: {
            name: 'Lionel Messi',
            age: 34,
            position: 'Forward',
            nationality: 'Argentinian',
            height: '1.70m',
            weight: '72kg',
            photo: 'https://example.com/messi.jpg',
            birth: {
                date: '1987-06-24',
                place: 'Rosario',
                country: 'Argentina'
            },
            teams: [],
            leagues: [],
            footballAPRating: {
                overall: 94,
                potential: 94,
                season: new Date().getFullYear(),
                league: {
                    id: 1,
                    name: 'Ligue 1',
                    logo: 'https://example.com/ligue1.jpg',
                    country: 'France',
                    flag: 'https://example.com/france_flag.jpg',
                    season: new Date().getFullYear(),
                },
            },
        },
        careerTimeline: [],
        stats: {
            games: {
                appearences: 30,
                lineups: 25,
                minutes: 2250,
                number: 10,
                position: 'Forward',
                rating: 8.5,
                captain: true,
            },
            substitutes: {
                in: 5,
                out: 10,
                bench: 2,
            },
            shots: {
                total: 100,
                on: 60,
            },
            goals: {
                total: 30,
                assists: 12,
            },
            passes: {
                total: 2000,
                key: 80,
            },
            tackles: {
                total: 40,
                successful: 30,
            },
            duels: {
                total: 150,
                won: 100,
            },
            dribbles: {
                total: 120,
                successful: 90,
            },
            fouls: {
                total: 15,
                committed: 10,
            },
            cards: {
                yellow: 3,
                red: 0,
            },
            penalty: {
                won: 5,
                scored: 4,
                missed: 1,
            },
        } as PlayerStats,
    };
}


export const mockTopSearchData = [
        {
            id: 1,
            name: 'Ligue 1',
            photo: 'https://example.com/ligue1.jpg',
            country: 'France',
            flag: 'https://example.com/france_flag.jpg',
            season: new Date().getFullYear(),
            type: 'league',
        },
        {
            id: 2,
            name: 'Premier League',
            photo: 'https://example.com/premierleague.jpg',
            country: 'England',
            flag: 'https://example.com/england_flag.jpg',
            season: new Date().getFullYear(),
            type: 'league',
        },
        {
            id: 10,
            name: 'Paris Saint-Germain',
            photo: 'https://example.com/psg.jpg',
            country: 'France',
            founded: 1970,
            stadium: 'Parc des Princes',
            type: 'team',
        },
        {
            id: 11,
            name: 'Manchester City',
            photo: 'https://example.com/mancity.jpg',
            country: 'England',
            founded: 1880,
            stadium: 'Etihad Stadium',
            type: 'team',
        },
        {
            id: 100,
            name: 'Lionel Messi',
            photo: 'https://example.com/messi.jpg',
            position: 'Forward',
            nationality: 'Argentinian',
            team: 'Paris Saint-Germain',
            type: 'player',
        },
        {
            id: 101,
            name: 'Kevin De Bruyne',
            photo: 'https://example.com/debruyne.jpg',
            position: 'Midfielder',
            nationality: 'Belgian',
            team: 'Manchester City',
            type: 'player',
        },
        {
            id: 102,
            name: 'Liam Cooper',
            photo: 'https://example.com/liamcooper.jpg',
            position: 'Defender',
            nationality: 'Scottish',
            team: 'Leeds United',
            type: 'player',
        },
        {
            id: 103,
            name: 'Lilian Thuram',
            photo: 'https://example.com/lilianthuram.jpg',
            position: 'Defender',
            nationality: 'French',
            team: 'Parma',
            type: 'player',
        },
        {
            id: 104,
            name: 'Lior Refaelov',
            photo: 'https://example.com/liorrefaelov.jpg',
            position: 'Midfielder',
            nationality: 'Israeli',
            team: 'Royal Antwerp',
            type: 'player',
        },
        {
            id: 105,
            name: 'Lindsey Horan',
            photo: 'https://example.com/lindseyhoran.jpg',
            position: 'Midfielder',
            nationality: 'American',
            team: 'Lyon',
            type: 'player',
        },
        {
            id: 106,
            name: 'Lino Sousa',
            photo: 'https://example.com/linosousa.jpg',
            position: 'Defender',
            nationality: 'English',
            team: 'Arsenal',
            type: 'player',
        },
        {
            id: 107,
            name: 'Liam Lawson',
            photo: 'https://example.com/liamlawson.jpg',
            position: 'Forward',
            nationality: 'New Zealander',
            team: 'Red Bull Salzburg',
            type: 'player',
        },
        {
            id: 108,
            name: 'Liana Salazar',
            photo: 'https://example.com/lianasalazar.jpg',
            position: 'Midfielder',
            nationality: 'Colombian',
            team: 'Santa Fe',
            type: 'player',
        },
        {
            id: 109,
            name: 'Liam Millar',
            photo: 'https://example.com/liammillar.jpg',
            position: 'Forward',
            nationality: 'Canadian',
            team: 'Basel',
            type: 'player',
        },
        {
            id: 110,
            name: 'Lina Magull',
            photo: 'https://example.com/linamagull.jpg',
            position: 'Midfielder',
            nationality: 'German',
            team: 'Bayern Munich',
            type: 'player',
        },
        {
            id: 111,
            name: 'Lina Hurtig',
            photo: 'https://example.com/linahurtig.jpg',
            position: 'Forward',
            nationality: 'Swedish',
            team: 'Arsenal',
            type: 'player',
        },
        {
            id: 112,
            name: 'Lindsey Thomas',
            photo: 'https://example.com/lindseythomas.jpg',
            position: 'Forward',
            nationality: 'French',
            team: 'AC Milan',
            type: 'player',
        },
        {
            id: 113,
            name: 'Lior Kroyter',
            photo: 'https://example.com/liorkroyter.jpg',
            position: 'Defender',
            nationality: 'Israeli',
            team: 'Maccabi Tel Aviv',
            type: 'player',
        },
        {
            id: 114,
            name: 'Lina Boussaha',
            photo: 'https://example.com/linaboussaha.jpg',
            position: 'Midfielder',
            nationality: 'French',
            team: 'Le Havre',
            type: 'player',
        },
        {
            id: 115,
            name: 'Lina Sahlén',
            photo: 'https://example.com/linasahlen.jpg',
            position: 'Defender',
            nationality: 'Swedish',
            team: 'Hammarby',
            type: 'player',
        },
        {
            id: 116,
            name: 'Lina Lehtovaara',
            photo: 'https://example.com/linalehtovaara.jpg',
            position: 'Goalkeeper',
            nationality: 'Finnish',
            team: 'KuPS',
            type: 'player',
        },
        {
            id: 117,
            name: 'Lina Nilsson',
            photo: 'https://example.com/linanilsson.jpg',
            position: 'Defender',
            nationality: 'Swedish',
            team: 'FC Rosengård',
            type: 'player',
        },
        {
            id: 118,
            name: 'Lina Chabane',
            photo: 'https://example.com/linachabane.jpg',
            position: 'Midfielder',
            nationality: 'Algerian',
            team: 'Paris FC',
            type: 'player',
        },
        {
            id: 119,
            name: 'Lina Spyridonidou',
            photo: 'https://example.com/linaspyridonidou.jpg',
            position: 'Forward',
            nationality: 'Greek',
            team: 'PAOK',
            type: 'player',
        },
        {
            id: 120,
            name: 'Lina Khelif',
            photo: 'https://example.com/linakhelif.jpg',
            position: 'Midfielder',
            nationality: 'Algerian',
            team: 'Grenoble',
            type: 'player',
        },
        {
            id: 121,
            name: 'Lina Gjorcheska',
            photo: 'https://example.com/linagjorcheska.jpg',
            position: 'Defender',
            nationality: 'Macedonian',
            team: 'Vardar',
            type: 'player',
        },
        {
            id: 122,
            name: 'Lina Larsson',
            photo: 'https://example.com/linalarsson.jpg',
            position: 'Defender',
            nationality: 'Swedish',
            team: 'Linköpings FC',
            type: 'player',
        },
        {
            id: 123,
            name: 'Lina Müller',
            photo: 'https://example.com/linamuller.jpg',
            position: 'Goalkeeper',
            nationality: 'German',
            team: 'SC Freiburg',
            type: 'player',
        },
        {
            id: 124,
            name: 'Lina Rask',
            photo: 'https://example.com/linarask.jpg',
            position: 'Goalkeeper',
            nationality: 'Swedish',
            team: 'KIF Örebro',
            type: 'player',
        },
        {
            id: 125,
            name: 'Lina Souloukou',
            photo: 'https://example.com/linasouloukou.jpg',
            position: 'Midfielder',
            nationality: 'Greek',
            team: 'Olympiacos',
            type: 'player',
        },
        {
            id: 126,
            name: 'Lina Tullberg',
            photo: 'https://example.com/linatullberg.jpg',
            position: 'Forward',
            nationality: 'Swedish',
            team: 'Djurgårdens IF',
            type: 'player',
        }
]