import { CoachCareerDto, TeamDto } from "../dtos/Teams";
import { Fixture, Team, Venue } from "../models/Fixtures";
import { Player, PlayerStats } from "../models/Players";
import { MatchStats, MatchStatsDetail } from "../models/Stats";

export const mockEmptyFixture = (): Fixture => ({
    league: {
      id: 0,
      name: 'Unknown League',
      logoUrl: '', // No logo available
    },
    kickoffDate: 'Date TBA', // Placeholder for unknown date
    kickoffTime: 'Time TBA', // Placeholder for unknown time
    venue: {
      name: 'Unknown Venue',
      city: 'Unknown City',
    } as Venue,
    homeTeam: {
      name: 'Unknown Home Team',
      teamId: 0,
      logoUrl: '', // No logo available
      short: 'HOME', // Optional: short name placeholder
    } as Team,
    awayTeam: {
      name: 'Unknown Away Team',
      teamId: 0,
      logoUrl: '', // No logo available
      short: 'AWAY', // Optional: short name placeholder
    } as Team,
});

export const mockEmptyStats = () => ({
    home: {
        shotsOnGoal: -1,
        shotsOffGoal: -1,
        totalShots: -1,
        blockedShots: -1,
        shotsInsideBox: -1,
        shotsOutsideBox: -1,
        fouls: -1,
        cornerKicks: -1,
        offsides: -1,
        ballPossession: -1,
        yellowCards: -1,
        redCards: -1,
        goalkeeperSaves: -1,
        totalPasses: -1,
        passesAccurate: -1,
        passesPercentage: -1,
        expectedGoals: "-1",
        goalsPrevented: -1,
    } as MatchStatsDetail,
    away: {
        shotsOnGoal: -1,
        shotsOffGoal: -1,
        totalShots: -1,
        blockedShots: -1,
        shotsInsideBox: -1,
        shotsOutsideBox: -1,
        fouls: -1,
        cornerKicks: -1,
        offsides: -1,
        ballPossession: -1,
        yellowCards: -1,
        redCards: -1,
        goalkeeperSaves: -1,
        totalPasses: -1,
        passesAccurate: -1,
        passesPercentage: -1,
        expectedGoals: "-1",
        goalsPrevented: -1,
    } as MatchStatsDetail,
} as MatchStats);

export const mockPlayer = (): Player => {
    return {
        info: {
            name: 'Unknown name',
            age: -1,
            position: 'Unknown position',
            nationality: 'Unknown nationality',
            height: 'Unknown height',
            weight: 'Unknown weight',
            photo: 'Unknown photo',
            birth: {
                date: 'Unknown birth date',
                place: 'Unknown birth place',
                country: 'Unknown birth country'
            },
            teams: [],
            leagues: [],
            footballAPRating: {
                overall: -1,
                potential: -1,
                season: -1,
                league: {
                    id: -1,
                    name: 'Unknown league name',
                    logo: 'Unknown league logo',
                    country: 'Unknown league country',
                    flag: 'Unknown league flag',
                    season: -1,
                },
            },
        },
        careerTimeline: [],
        stats: {
            games: {
                appearences: -1,
                lineups: -1,
                minutes: -1,
                number: -1,
                position: 'Unknown games position',
                rating: -1,
                captain: false,
            },
            substitutes: {
                in: -1,
                out: -1,
                bench: -1,
            },
            shots: {
                total: -1,
                on: -1,
            },
            goals: {
                total: -1,
                assists: -1,
            },
            passes: {
                total: -1,
                key: -1,
            },
            tackles: {
                total: -1,
                successful: -1,
            },
            duels: {
                total: -1,
                won: -1,
            },
            dribbles: {
                total: -1,
                successful: -1,
            },
            fouls: {
                total: -1,
                committed: -1,
            },
            cards: {
                yellow: -1,
                red: -1,
            },
            penalty: {
                won: -1,
                scored: -1,
                missed: -1,
            },
        } as PlayerStats,
    };
}

export const mockTeamDetails = (): TeamDto => {
    return {
        _id: 'team_unknown_001',
        team_id: 0,
        team_name: 'Unknown Team',
        coach: {
            id: 0,
            name: 'Unknown Coach',
            firstname: 'Unknown',
            lastname: 'Unknown',
            age: -1,
            nationality: 'Unknown',
            photo: '',
            height: "",
            weight: "",
            team: {
                id: 0,
                name: 'Unknown Team',
                logo: '',
            },
            birth: {
                date: '',
                place: 'Unknown',
                country: 'Unknown',
            },
            career: []
        },
        current_squad: [],
        past_fixtures: [],
        future_fixtures: []
    }
}

export const mockTopSearchData = [
        {
            id: 1,
            name: 'Ligue 1',
            photo: 'https://example.com/ligue1.jpg',
            country: 'France',
            flag: 'https://example.com/france_flag.jpg',
            season: new Date().getFullYear(),
            type: 'league',
        },
        {
            id: 2,
            name: 'Premier League',
            photo: 'https://example.com/premierleague.jpg',
            country: 'England',
            flag: 'https://example.com/england_flag.jpg',
            season: new Date().getFullYear(),
            type: 'league',
        },
        {
            id: 10,
            name: 'Paris Saint-Germain',
            photo: 'https://example.com/psg.jpg',
            country: 'France',
            founded: 1970,
            stadium: 'Parc des Princes',
            type: 'team',
        },
        {
            id: 11,
            name: 'Manchester City',
            photo: 'https://example.com/mancity.jpg',
            country: 'England',
            founded: 1880,
            stadium: 'Etihad Stadium',
            type: 'team',
        },
        {
            id: 100,
            name: 'Lionel Messi',
            photo: 'https://example.com/messi.jpg',
            position: 'Forward',
            nationality: 'Argentinian',
            team: 'Paris Saint-Germain',
            type: 'player',
        },
        {
            id: 101,
            name: 'Kevin De Bruyne',
            photo: 'https://example.com/debruyne.jpg',
            position: 'Midfielder',
            nationality: 'Belgian',
            team: 'Manchester City',
            type: 'player',
        },
        {
            id: 102,
            name: 'Liam Cooper',
            photo: 'https://example.com/liamcooper.jpg',
            position: 'Defender',
            nationality: 'Scottish',
            team: 'Leeds United',
            type: 'player',
        },
        {
            id: 103,
            name: 'Lilian Thuram',
            photo: 'https://example.com/lilianthuram.jpg',
            position: 'Defender',
            nationality: 'French',
            team: 'Parma',
            type: 'player',
        },
        {
            id: 104,
            name: 'Lior Refaelov',
            photo: 'https://example.com/liorrefaelov.jpg',
            position: 'Midfielder',
            nationality: 'Israeli',
            team: 'Royal Antwerp',
            type: 'player',
        },
        {
            id: 105,
            name: 'Lindsey Horan',
            photo: 'https://example.com/lindseyhoran.jpg',
            position: 'Midfielder',
            nationality: 'American',
            team: 'Lyon',
            type: 'player',
        },
        {
            id: 106,
            name: 'Lino Sousa',
            photo: 'https://example.com/linosousa.jpg',
            position: 'Defender',
            nationality: 'English',
            team: 'Arsenal',
            type: 'player',
        },
        {
            id: 107,
            name: 'Liam Lawson',
            photo: 'https://example.com/liamlawson.jpg',
            position: 'Forward',
            nationality: 'New Zealander',
            team: 'Red Bull Salzburg',
            type: 'player',
        },
        {
            id: 108,
            name: 'Liana Salazar',
            photo: 'https://example.com/lianasalazar.jpg',
            position: 'Midfielder',
            nationality: 'Colombian',
            team: 'Santa Fe',
            type: 'player',
        },
        {
            id: 109,
            name: 'Liam Millar',
            photo: 'https://example.com/liammillar.jpg',
            position: 'Forward',
            nationality: 'Canadian',
            team: 'Basel',
            type: 'player',
        },
        {
            id: 110,
            name: 'Lina Magull',
            photo: 'https://example.com/linamagull.jpg',
            position: 'Midfielder',
            nationality: 'German',
            team: 'Bayern Munich',
            type: 'player',
        },
        {
            id: 111,
            name: 'Lina Hurtig',
            photo: 'https://example.com/linahurtig.jpg',
            position: 'Forward',
            nationality: 'Swedish',
            team: 'Arsenal',
            type: 'player',
        },
        {
            id: 112,
            name: 'Lindsey Thomas',
            photo: 'https://example.com/lindseythomas.jpg',
            position: 'Forward',
            nationality: 'French',
            team: 'AC Milan',
            type: 'player',
        },
        {
            id: 113,
            name: 'Lior Kroyter',
            photo: 'https://example.com/liorkroyter.jpg',
            position: 'Defender',
            nationality: 'Israeli',
            team: 'Maccabi Tel Aviv',
            type: 'player',
        },
        {
            id: 114,
            name: 'Lina Boussaha',
            photo: 'https://example.com/linaboussaha.jpg',
            position: 'Midfielder',
            nationality: 'French',
            team: 'Le Havre',
            type: 'player',
        },
        {
            id: 115,
            name: 'Lina Sahlén',
            photo: 'https://example.com/linasahlen.jpg',
            position: 'Defender',
            nationality: 'Swedish',
            team: 'Hammarby',
            type: 'player',
        },
        {
            id: 116,
            name: 'Lina Lehtovaara',
            photo: 'https://example.com/linalehtovaara.jpg',
            position: 'Goalkeeper',
            nationality: 'Finnish',
            team: 'KuPS',
            type: 'player',
        },
        {
            id: 117,
            name: 'Lina Nilsson',
            photo: 'https://example.com/linanilsson.jpg',
            position: 'Defender',
            nationality: 'Swedish',
            team: 'FC Rosengård',
            type: 'player',
        },
        {
            id: 118,
            name: 'Lina Chabane',
            photo: 'https://example.com/linachabane.jpg',
            position: 'Midfielder',
            nationality: 'Algerian',
            team: 'Paris FC',
            type: 'player',
        },
        {
            id: 119,
            name: 'Lina Spyridonidou',
            photo: 'https://example.com/linaspyridonidou.jpg',
            position: 'Forward',
            nationality: 'Greek',
            team: 'PAOK',
            type: 'player',
        },
        {
            id: 120,
            name: 'Lina Khelif',
            photo: 'https://example.com/linakhelif.jpg',
            position: 'Midfielder',
            nationality: 'Algerian',
            team: 'Grenoble',
            type: 'player',
        },
        {
            id: 121,
            name: 'Lina Gjorcheska',
            photo: 'https://example.com/linagjorcheska.jpg',
            position: 'Defender',
            nationality: 'Macedonian',
            team: 'Vardar',
            type: 'player',
        },
        {
            id: 122,
            name: 'Lina Larsson',
            photo: 'https://example.com/linalarsson.jpg',
            position: 'Defender',
            nationality: 'Swedish',
            team: 'Linköpings FC',
            type: 'player',
        },
        {
            id: 123,
            name: 'Lina Müller',
            photo: 'https://example.com/linamuller.jpg',
            position: 'Goalkeeper',
            nationality: 'German',
            team: 'SC Freiburg',
            type: 'player',
        },
        {
            id: 124,
            name: 'Lina Rask',
            photo: 'https://example.com/linarask.jpg',
            position: 'Goalkeeper',
            nationality: 'Swedish',
            team: 'KIF Örebro',
            type: 'player',
        },
        {
            id: 125,
            name: 'Lina Souloukou',
            photo: 'https://example.com/linasouloukou.jpg',
            position: 'Midfielder',
            nationality: 'Greek',
            team: 'Olympiacos',
            type: 'player',
        },
        {
            id: 126,
            name: 'Lina Tullberg',
            photo: 'https://example.com/linatullberg.jpg',
            position: 'Forward',
            nationality: 'Swedish',
            team: 'Djurgårdens IF',
            type: 'player',
        }
]